### ISSUE TITLE
Broken on iOS as of 1.2.2 CLI

### ISSUE THREAD

**Issue by maknz** [telerik/nativescript-ui-samples#14]
We've upgraded our CLI to 1.2.2 which is the latest stable. The JS runtime is no longer able to find the Telerik UI iOS constants:

> ReferenceError: Can't find variable: TKSideDrawerDelegate.

There were some tweaks done in 1.2.2  I understand that could affect this, around paths in the .pbxproj file.

Android is working fine.

**Comment by ginev** [comment]
Hi @maknz,

Thanks for reporting this. We've managed to reproduce it and identify the root cause. We are working on addressing it.

**Comment by emiloberg** [comment]
+1

**Comment by siberian1967** [comment]
+1 seems broken still? 
```
tns --version
1.5.1
```
and in my logs
```
Dec 10 12:16:02 Johns-MacBook-Pro sampleGroceries[20400]: file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:273:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
```

Any ETA on a fix or do I need to upgrade something?

**Comment by gergderkson** [comment]
I'm still seeing this issue on iOS. Was there a fix?

**Comment by kn4rfy** [comment]
I got this issue today.

> Aug  3 18:55:41 kn4rfy Pikommerce[24531]: file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:314:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

**Comment by flq** [comment]
To elaborate: If you look into the code of `nativescript-telerik-ui/sidedrawer/sidedrawer.ios.js`, line 314, there is the line

    TKSideDrawerDelegateImpl.ObjCProtocols = [TKSideDrawerDelegate];

where `TKSideDrawerDelegate`  indeed seems to be coming from nowhere

**Comment by ginev** [comment]
@flq @gergderkson @kn4rfy this is a TypeScript issue. It should not prevent you from using the component in your application. Sometimes TypeScript declarations are not correctly resolved causing similar errors.

**Comment by flq** [comment]
OK, I am afraid that this does really bug me at runtime...

```
Aug  4 21:51:52 Franks-MBP countStuff[3850]: file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:314:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
Aug  4 21:51:52 Franks-MBP com.apple.CoreSimulator.SimDevice.2015B134-2C87-4C20-AD05-54174901D681.launchd_sim[3744] (UIKitApplication:org.nativescript.countStuff[0x51da][3850]): Service exited due to signal: Segmentation fault: 11
```

I am sailing pretty close to the samples, so I am not sure what is happening

**Comment by shlomiassaf** [comment]
Happens to me as well.

@ginev, the error states: JS Reference Error... so it's not a typescript error.

**Comment by shlomiassaf** [comment]
Ok, now it does not appear.

I can't retrace but I suggest removing platform/ios `rm -rf platform/ios`

**Comment by flq** [comment]
You mean removing and adding platform again? Is this the canonical way to update dependencies?

**Comment by shlomiassaf** [comment]
@flq I don't think so... I think there are some caching issues from time to time.
When I have an issue I can't solve for more then 5 minutes first thing is to clear cache :) It helped several times...

**Comment by jasonhealy** [comment]
@ginev - Still getting this on IOS  - Considering purchasing pro.. Is there a fix or workaround even?

`JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate`

**Comment by Habeeb-mohamed** [comment]
@ginev - Do we have fix for this issue?

**Comment by Daxito** [comment]
All,
Maybe you should also remove the file under lib/iOS/TelerikUI.framework
That fixed some issues for me in the past, now everytime there is a new version of this plugin I just deleted that file so that I get a clean one.

**Comment by ginev** [comment]
@Habeeb-mohamed @Daxito we cannot reproduce this issue with the latest versions of NS and NS UI.

**Comment by Habeeb-mohamed** [comment]
I updated core and nativescript to 2.4@next, For me it is working fine. Thanks a lot

**Comment by stefalda** [comment]
Hi, I confirm that It's broken with NS 2.3 and NS UI 1.4.1

**Comment by stefalda** [comment]
With version @next version (2.4) I get another error: 
`undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')`

**Comment by stefalda** [comment]
With @next version it seems to work...

**Comment by NgSculptor** [comment]
Still facing this issue with 2.3 core and ui. Tried updating to @next and ended up with 2.5.x which is also throwing same errors. Is there a fix available?

**Comment by NgSculptor** [comment]
Upgraded to 

"nativescript-telerik-ui": "^1.5.0-2016.11.4.1", and 
"tns-core-modules": "^2.5.0-2016-11-04-4670"

Global nativescript is still 2.3.0

stack trace:



> MacBook-Pro:sample-Groceries km$ tns livesync ios --emulator --watch
Executing before-prepare hook from /Users/km/Documents/Projects/test-ns/sample-Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-social-share for ios.
Successfully prepared plugin nativescript-telerik-ui for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Project successfully prepared (ios)
Executing before-livesync hook from /Users/km/Documents/Projects/test-ns/sample-Groceries/hooks/before-livesync/nativescript-angular-sync.js
Transferring project files...
Successfully transferred all files.
Applying changes...
Successfully synced application org.nativescript.groceries on device BF9ACC2E-9F9A-40FD-9C2E-E0885F9C313A.
Executing before-watch hook from /Users/km/Documents/Projects/test-ns/sample-Groceries/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Nov  4 14:13:28 MacBook-Pro sampleGroceries[47774]: objc[47774]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11aaaf998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11a8d4d38). One of the two will be used. Which one is undefined.
Nov  4 14:13:29 MacBook-Pro sampleGroceries[47774]: 1   0x103e318d7 -[TNSRuntime executeModule:]
Nov  4 14:13:29 MacBook-Pro sampleGroceries[47774]: 2   0x1039db6d2 main
Nov  4 14:13:29 MacBook-Pro sampleGroceries[47774]: 3   0x107d4c68d start
Nov  4 14:13:29 MacBook-Pro sampleGroceries[47774]: 4   0x1
Nov  4 14:13:29 MacBook-Pro sampleGroceries[47774]: file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:320:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate
Nov  4 14:13:29 MacBook-Pro com.apple.CoreSimulator.SimDevice.BF9ACC2E-9F9A-40FD-9C2E-E0885F9C313A.launchd_sim[41762] (UIKitApplication:org.nativescript.groceries[0xdebe][47774]): Service exited due to Segmentation fault: 11
2:13:31 PM - Compilation complete. Watching for file changes.

**Comment by ginev** [comment]
@NgSculptor easiest way to debug would be to take a look at the project as see what goes wrong. Can you ZIP it and share it somehow?

**Comment by NgSculptor** [comment]
Thank you but it is resolved, just removed and added it a few times

**Comment by Emiilly** [comment]
@NgSculptor  Removed what exactly? I am getting the same error.

**Comment by NgSculptor** [comment]
`tns-core-modules`

**Comment by Taremeh** [comment]
Same issue, app crashes (with latest tns-core-modules version 2.3.0):
```
file:///app/tns_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.js:316:67: JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate

(UIKitApplication:org.nativescript.apphovenAlpha[0xcf1e][21838]): Service exited due to Segmentation fault: 11
```

I uninstalled and installed `tns-core-modules` a couple of times, but it didn't help. I would have been suprised if it would have worked out...

Any quick fixes? Or is this a deeper problem? Because the android version works fine.

**Comment by soeyanmin** [comment]
Still having this issue even after applied suggested above in iOS but android is working fine.
JS ERROR ReferenceError: Can't find variable: TKSideDrawerDelegate.

Thanks for the help

**Comment by ghys** [comment]
+1

**Comment by ginev** [comment]
Hello @soeyanmin and @ghys,

We are not able to reproduce this behavior. Can you paste your package.json here, as well as share your TypeScript version so that we can try to reproduce?

**Comment by ghys** [comment]
Hi @ginev, sorry I forgot to mention I got it working again by simply upgrading all NativeScript components to 2.5, following http://docs.nativescript.org/releases/upgrade-instructions.
Thank you!
